apiVersion: v1
kind: Service
metadata:
  name: digitify-app
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: digitify-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
